services:


  api-gateway:
    image: nginx:1.27-alpine
    container_name: facoffee-api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
      - users-service
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - facoffee-net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: facoffee-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - facoffee-net

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: facoffee-keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    networks:
      - facoffee-net

  mailpit:
    image: axllent/mailpit:v1.20
    container_name: facoffee-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - facoffee-net

  users-db:
    image: postgres:16-alpine
    container_name: facoffee-users-db
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users123
    ports:
      - "5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data
    networks:
      - facoffee-net

  users-service:
    build: ./services/users-service
    container_name: facoffee-users-service
    ports:
      - "3001:3001"
    environment:
      DB_HOST: users-db
      DB_PORT: 5432
      DB_NAME: usersdb
      DB_USER: users
      DB_PASSWORD: users123
    depends_on:
      - users-db
    networks:
      - facoffee-net

volumes:
  users_db_data:

networks:
  facoffee-net:
    driver: bridge